var matchData =	[{ id: '98',
    season: '2008',
    city: 'Delhi',
    date: '2008-05-15',
    team1: 'Delhi Daredevils',
    team2: 'Deccan Chargers',
    toss_winner: 'Deccan Chargers',
    toss_decision: 'field',
    result: 'normal',
    dl_applied: '0',
    winner: 'Delhi Daredevils',
    win_by_runs: '12',
    win_by_wickets: '0',
    player_of_match: 'A Mishra',
    venue: 'Feroz Shah Kotla',
    umpire1: 'BG Jerling',
    umpire2: 'GA Pratapkumar',
    umpire3: '' },
  { id: '99',
    season: '2008',
    city: 'Mumbai',
    date: '2008-05-16',
    team1: 'Kolkata Knight Riders',
    team2: 'Mumbai Indians',
    toss_winner: 'Mumbai Indians',
    toss_decision: 'field',
    result: 'normal',
    dl_applied: '0',
    winner: 'Mumbai Indians',
    win_by_runs: '0',
    win_by_wickets: '8',
    player_of_match: 'SM Pollock',
    venue: 'Wankhede Stadium',
    umpire1: 'BR Doctrove',
    umpire2: 'DJ Harper',
    umpire3: '' }]


    var deliveries = [{ match_id: '1',
    inning: '1',
    batting_team: 'Sunrisers Hyderabad',
    bowling_team: 'Royal Challengers Bangalore',
    over: '16',
    ball: '6',
    batsman: 'DJ Hooda',
    non_striker: 'Yuvraj Singh',
    bowler: 'YS Chahal',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
    extra_runs: '0',
    total_runs: '1',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '' },
  { match_id: '1',
    inning: '1',
    batting_team: 'Sunrisers Hyderabad',
    bowling_team: 'Royal Challengers Bangalore',
    over: '17',
    ball: '1',
    batsman: 'DJ Hooda',
    non_striker: 'Yuvraj Singh',
    bowler: 'TS Mills',
    is_super_over: '0',
    wide_runs: '0',
    bye_runs: '0',
    legbye_runs: '0',
    noball_runs: '0',
    penalty_runs: '0',
    batsman_runs: '1',
    extra_runs: '0',
    total_runs: '1',
    player_dismissed: '',
    dismissal_kind: '',
    fielder: '' }]
